# Generated by Django 2.0.5 on 2018-06-08 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('active', models.BooleanField(default=True)),
                ('time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30, primary_key=True, serialize=False)),
                ('password', models.TextField(default='')),
                ('token', models.TextField(default='')),
            ],
        ),
    ]
